### ISSUE TITLE
Any way to support retrieving URLs?

### ISSUE THREAD

**Issue by Chinese1904** [spatie/flysystem-dropbox#12]
Hi everyone,

I am not too familiar with this flysystem and with Dropbox in general, but are we able to retrieve URLs with this? Or am I doing something wrong?

Thanks,

Chris

**Comment by freekmurze** [comment]
Currently the driver has no method to do that, because the interface that needs to be implemented doesn't require it.

However, I'd accept a PR that adds and `url` method to frameworks like Laravel can make use of it.

**Comment by Darival** [comment]
hi, i'd like to work on this.

i believe what we need is to make use of createSharedLinkWithSettings in the dropbox client.
