### ISSUE TITLE
could not list/get subfolders

### ISSUE THREAD

**Issue by OskarStark** [spatie/flysystem-dropbox#16]
Could not list subfolders:

```php
$client = $this->getContainer()->get('dropbox.client');
$adapter = new DropboxAdapter($client);
$flysystem = new Filesystem($adapter);

$folders = $flysystem->listContents('FOO');
dump($folders);
```
produces:
```php
array:9 [
  0 => array:5 [
    "path" => "FOO/BAR"
    "type" => "dir"
    "dirname" => "FOO"
    "basename" => "BAR"
    "filename" => "BAR"
  ]
  1 => array:5 [
    "path" => "FOO/BAZ"
    "type" => "dir"
    "dirname" => "FOO"
    "basename" => "BAZ"
    "filename" => "BAZ"
  ]
```

the next part should show the content of `FOO/BAR`:
```php
$files = $flysystem->listContents($folders[0]['path']);
```

but this returns an empty array. When i switch to a local adapter, my code is working...
any ideas?

When I use this:
```php
$client = $this->getContainer()->get('dropbox.client');
$adapter = new DropboxAdapter($client);
$flysystem = new Filesystem($adapter);

$folders = $flysystem->listContents('FOO/BAR');
```

I get the following error message:
![screenshot 2017-06-19 15 27 07](https://user-images.githubusercontent.com/995707/27287390-c54b871c-5503-11e7-9943-e8d095fe1f4b.png)

**Comment by freekmurze** [comment]
I know Dropbox is a little bit tricky with capitals. Could you make
everything lowercase?





Freek Van der Herten
Samberstraat 69 D
2060 Antwerpen
T:  +32 3 292 56 79
M: +32 495 84 27 91
https://spatie.be

**Comment by OskarStark** [comment]
You rename the folder on dropbox.com or use `foo/bar`?

**Comment by freekmurze** [comment]
both

**Comment by OskarStark** [comment]
good to know, thank you for your feedback :+1:

**Comment by freekmurze** [comment]
If my suggestion did not work, reopen the PR.

**Comment by vesper8** [comment]
@OskarStark did you figure it out? i've tried every combination and I can only list the contents of root folders, not subfolders. Also if I use the Spatie Dropbox API package directly, without making the flysystem adapter I mean, then I have no problem listing full paths

**Comment by OskarStark** [comment]
Are you using the cached adapter?

**Comment by xavierhb** [comment]
I have the exact same issue you originally posted @OskarStark. And same as @vesper8, if I do the same with local driver it works. Any ideas? I'm not using the cached adapter.
