### ISSUE TITLE
Include the service provider in the package

### ISSUE THREAD

**Issue by sebastiaanluca** [spatie/flysystem-dropbox#17]
Would it perhaps be a good idea to include the service provider mentioned in the blog post in this package? It feels a bit weird we still have to extend the storage adapter manually when that's the main use-case for most. Creating and maintaining a custom Dropbox service provider for each project that uses it (and I have _a lot_ of projects depending on it) is also quite redundant.

**Comment by freekmurze** [comment]
I'd like to keep this package framework agnostic.

You're of course free to create your own package with that service provider.

**Comment by sebastiaanluca** [comment]
Thanks for the reply, makes sense.

**Comment by S43534** [comment]
For reference: https://github.com/benjamincrozat/laravel-dropbox-driver
