### ISSUE TITLE
PHP 7.1 support?

### ISSUE THREAD

**Issue by ricpelo** [spatie/flysystem-dropbox#21]
When I do `composer require spatie/flysystem-dropbox` in my project, I get the following error:

```
Using version ^1.0 for spatie/flysystem-dropbox
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ~7.0.0 but your PHP version (7.1.8) does not satisfy that requirement.


Installation failed, reverting ./composer.json to its original content.
```

**Comment by freekmurze** [comment]
Strange, composer.json seem to have the right constraint

https://github.com/spatie/flysystem-dropbox/blob/master/composer.json#L23

And I'm able to install the package on my machine with PHP 7.1

**Comment by ricpelo** [comment]
Oops! Sorry, my fault. I just realized my `composer.json` had a typo :(.
Thank you for your fast reply and sorry again!
