### ISSUE TITLE
Is there a way to change on the fly the token?

### ISSUE THREAD

**Issue by fullstackdevelope** [spatie/flysystem-dropbox#23]
each user has it's dropbox token in db , and I need to set the token before i try to use the disk,

**Question**: how can I change the token so I could write in each users's folders?

**Comment by AlexVanderbist** [comment]
There's no way to change the `DropboxClient` or its `accessToken` once the `DropboxAdapter` is instantiated. This means you'll have to create a new `DropboxClient` and `DropboxAdapter` instance for every user.
