### ISSUE TITLE
Download very slow

### ISSUE THREAD

**Issue by VincentClair** [spatie/flysystem-dropbox#24]
Do you experience any very slow download experience ?
Actually, to synchronise just an html theme (25 files for 2Mb), it takes from 30s to 60s.

Here is my code : 
```
$manager = new MountManager(['remote' => $this->getRemoteFileSystem(), 'temp' => $this->temp]);
        $remote = 'remote://';
        $temp = 'temp://';

        $files = $manager->listContents($remote, true);
        foreach ($files as $file) {
            if ($file['type'] === 'file') {
                $manager->copy($remote . $file['path'], $temp . $path . '/' . $file['path'], ['disable_asserts' => true]);
            }
        }
```

Have you some advices to drastically increase just download speed ?
Thanks in advance !

**Comment by freekmurze** [comment]
Didn't have this problem myself and probably the slowness isn't caused by this package.

**Comment by VincentClair** [comment]
Sorry to bother you !
I've many tests on fibre networks from different internet providers and it's always slow.
Or maybe it's the location: i'm from France.
Do you have a paid account for Dropbox ? I have a free one and its come from there.
Thanks for your help.

**Comment by freekmurze** [comment]
I have used non paid accounts with this. If speed is a problem, best file a support ticket at Dropbox itself (or ask your ISP).
