### ISSUE TITLE
DropboxAdapter::listContents() doesn't take "has_more" value into account

### ISSUE THREAD

**Issue by joe-walker** [spatie/flysystem-dropbox#26]
Currently, `DropboxAdapter::listContents()` calls `Client::listFolder()`, does some processing on `$result['entries']` if any are present, and returns the entries.

If I understand correctly, I think that this needs to also take into account the possibility that not all results are returned with the first request and instead `$result['has_more']` may be TRUE, which means that `Client::listFolderContinue($result['cursor'])` should be called in a loop, collecting all entries until `$result['has_more']` is FALSE.

The code for `listContents()` could be changed to something like this:

    public function listContents($directory = '', $recursive = false): array
    {
        $location = $this->applyPathPrefix($directory);

        $result = $this->client->listFolder($location, $recursive);
        $entries = $result['entries'];

        while ($result['has_more']) {
            $result = $this->client->listFolderContinue($result['cursor']);
            $entries = array_merge($entries, $result['entries']);
        }

        if (! count($entries)) {
            return [];
        }

        return array_map(function ($entry) {
            $path = $this->removePathPrefix($entry['path_display']);

            return $this->normalizeResponse($entry, $path);
        }, $entries);
    }

**Comment by freekmurze** [comment]
I'd accept a fully tested PR that improves the function.
