### ISSUE TITLE
The Dropbox API v2 does not support mimetypes

### ISSUE THREAD

**Issue by MickaelTH** [spatie/flysystem-dropbox#29]
Hi,

First, thanks for your work on this piece of software.

I am using it with Laravel 5.4 as provider for flysystem, included to elFinder.

Found a weird issue, not sure it is related to your script but maybe you found this before. I can see the folders, but then I cannot access folders with files:

![2017-11-18 002318](https://user-images.githubusercontent.com/26375917/32979422-9e5b08e8-cc87-11e7-8093-8f01d1c665f6.png)

Any idea? Thanks.

**Comment by freekmurze** [comment]
Can you provide a PHP code sample that results in this error?

**Comment by robbytaylor** [comment]
I just ran into this problem as well. The exception is thrown by any call to getMimetype() when using the Dropbox adaptor.

https://github.com/spatie/flysystem-dropbox/blob/master/src/DropboxAdapter.php#L232

I've worked around the issue for now by editing the Dropbox adaptor to calculate the mimetype from the filename, which is how the FTP Flysystem adaptor works:

https://github.com/thephpleague/flysystem/blob/master/src/Adapter/Ftp.php#L415

Would you accept a PR which adds the behaviour from the FTP driver to this package?

**Comment by freekmurze** [comment]
Yup! 👍

**Comment by freekmurze** [comment]
Fixed in #30

**Comment by MickaelTH** [comment]
Just to confirm the fix is working fine, thank you very much!
