### ISSUE TITLE
Support of Filesystem Disks 'root' variable

### ISSUE THREAD

**Issue by MickaelTH** [spatie/flysystem-dropbox#31]
Hi,

Just a question here, not a bug - I think. Anyway to make the use of Filesystem with a root folder?

I tried like my other disks but seems to be ignored and always start at the root of Dropbox.

![2017-11-19 002319](https://user-images.githubusercontent.com/26375917/32987471-8f288178-cd1f-11e7-9f8a-72638e47ae73.png)

I suspect this is ignored by the Dropbox API, but maybe I am missing something.

**Comment by freekmurze** [comment]
This driver does not use `root` setting. I'd accept a fully tested PR that adds support for `root` to the package.

**Comment by OskarStark** [comment]
This would be a nice improvement.
@MickaelTH would you send a PR?

**Comment by freekmurze** [comment]
Closing this for now. We'll continue the conversation when a PR comes in.
