### ISSUE TITLE
Class cache does not exist error

### ISSUE THREAD

**Issue by subdesign** [spatie/flysystem-dropbox#32]
I use this package with laravel-backup, and if I add the new spatie provider to `app.php` I get the error in the title. But only on my live server. If I comment out the provider in app.php, of course the backup doesn't work but my site run, and no cache error happens.  
Any idea what should be the problem? And why I don't have any issue on local dev environment? At local db backup made and upped to dropbox as it should.
the code base is the same, of course, I deploy the code with git. 

How the Dropbox storage driver could be related to cache handling?

I use Laravel 5.5 latest. 

thanks

**Comment by freekmurze** [comment]
I guess this has something to do with how you configured your app in you production environment and not with this package itself.
