### ISSUE TITLE
get link

### ISSUE THREAD

**Issue by ronald169** [spatie/flysystem-dropbox#43]
**How can I get link to uploaded file on dropbox**

**Comment by ClProsser** [comment]
Just use [createSharedLinkWithSettings](https://github.com/spatie/flysystem-dropbox/blob/ed19482a1a221250a6b702ff2125be182cf4120f/src/DropboxAdapter.php#L258)

![cmd_2019-05-30_13-28-21](https://user-images.githubusercontent.com/47798395/58630188-ee11b800-82de-11e9-93d9-5e140e5b125d.png)
