### ISSUE TITLE
use token per User

### ISSUE THREAD

**Issue by arce701** [spatie/flysystem-dropbox#48]
Good day, sorry for writing here, I need to save the dropbox tokens in a database for each user, so that when the logged user uploads a file it is saved in his personal dropbox. Some advice or example I would appreciate very much.

**Comment by atymic** [comment]
Just pass it when creating the dropbox client:

```php

use League\Flysystem\Filesystem;
use Spatie\Dropbox\Client;
use Spatie\FlysystemDropbox\DropboxAdapter;

$client = new Client($user->dropbox_token);

$adapter = new DropboxAdapter($client);

$filesystem = new Filesystem($adapter);
```
