### ISSUE TITLE
Add compatibility with flysystem v2

### ISSUE THREAD

**Issue by jmsche** [spatie/flysystem-dropbox#58]

**Comment by SlvrEagle23** [comment]
Been working on migrating my project to Flysystem v2 and it uses the Dropbox adapter, so I took it on myself to fork this repo and write up a version that's compatible with Flysystem v2:

https://github.com/SlvrEagle23/flysystem-dropbox/tree/feature/flysystem-2.x

At this point it has full interface compatibility and a passing test suite.

Happy to work with the folks on this repository to PR it in for inclusion here. :)

**Comment by freekmurze** [comment]
Feel free to PR the needed changes for v2 to this repo! I'll create a new major version, so breaking changes are allowed. Make sure all tests pass and that the readme is updated 👍

**Comment by freekmurze** [comment]
Compatibility with v2 of Flysystem is coming later today.
