### ISSUE TITLE
Unable to install on Laravel 8.35.1 - requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by nhtahoe** [spatie/flysystem-dropbox#67]
Trying to install but getting the following error:

```
forge@example-dev-1:~/devapi.example.com$ composer require spatie/flysystem-dropbox
Using version ^2.0 for spatie/flysystem-dropbox
./composer.json has been updated
Running composer update spatie/flysystem-dropbox
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/flysystem-dropbox[2.0.0, ..., v2.x-dev] require league/flysystem ^2.0.4 -> found league/flysystem[2.0.4, 2.x-dev] but the package is fixed to 1.1.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires spatie/flysystem-dropbox ^2.0 -> satisfiable by spatie/flysystem-dropbox[2.0.0, 2.0.1, 2.0.2, v2.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

I have the latest version of spatie/laravel-backup installed and I believe this might be due to a conflict with [line 29 of composer.json in spatie/laravel-backup](https://github.com/spatie/laravel-backup/blob/master/composer.json#L29) where it is requiring `"league/flysystem": "^1.0.49|^2.0",`

Couldn't quite figure out how to resolve the problem on my own, so creating the issue here.

**Comment by freekmurze** [comment]
Laravel isn't compatible with Flysystem 2 at the moment. Support will arrive in Laravel 9 due to be release in September.

**Comment by nhtahoe** [comment]
> Laravel isn't compatible with Flysystem 2 at the moment. Support will arrive in Laravel 9 due to be release in September.

Oh, got it, I was not aware of that fact. Thank you, and I truly appreciate all the amazing work you do for the community @freekmurze!

**Comment by samuelhgf** [comment]
@nhtahoe Here is a solution with didn't find out yet 
https://laracasts.com/discuss/channels/laravel/could-not-installed-spatieflysystem-dropbox-package-on-laravel-8351-version-reason-of-some-dependecies

**Comment by nhtahoe** [comment]
Thanks @samuelhgf - running `composer require spatie/flysystem-dropbox "^1.0.0"` did the trick!

**Comment by Bazzly** [comment]
ok cool
