### ISSUE TITLE
Add compatibility for Flysystem 3

### ISSUE THREAD

**Issue by BlackbitDevs** [spatie/flysystem-dropbox#88]
Flysystem 3 is available since almost 1 year. Currently there is no compatible Dropbox adapter for this. Could you add support for this? Actually it does not look to be that complicated according to [the release blog post](https://blog.frankdejonge.nl/flysystem-3-0-0-is-released/#what-changed) and the [update instructions](https://flysystem.thephpleague.com/docs/what-is-new/)

Actually it says 
> Since V2, V3 has been released which is backwards compatible from a consumption point of view, but it has a BC break for custom adapter implementations.

Don't know how much work this would mean...

**Comment by freekmurze** [comment]
It's already compatible: https://github.com/spatie/flysystem-dropbox/blob/60ac0f929da31aa1321b4b2ac2ca0ba961e4664a/composer.json
